
- name: Install Python and pip
  become: yes
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install Flask dependencies
  become: yes
  ansible.builtin.pip:
    name: flask
    state: present

- name: Copy Flask app files
  ansible.builtin.copy:
    src: "../../app/"
    dest: /home/ec2-user/app/
    mode: '0755'

- name: Create systemd service file for Flask app
  become: yes
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/flask.service"
    dest: /etc/systemd/system/flask.service
    mode: '0644'
  notify: Restart Flask service

- name: Ensure Flask service is enabled and started
  become: yes
  ansible.builtin.systemd:
    name: flask
    enabled: yes
    state: started

- name: Install CloudWatch Agent
  become: yes
  ansible.builtin.command: yum install -y amazon-cloudwatch-agent
  register: install_result
  changed_when: install_result.rc == 0 and 'is already installed' not in install_result.stdout_lines | join('')
  when: ansible_os_family == "RedHat"

- name: Start CloudWatch Agent
  become: yes
  ansible.builtin.service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes

- name: Copy CloudWatch config
  become: yes
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/cloudwatch-config.json"
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    mode: '0644'
  notify: Restart CloudWatch Agent

- name: Ensure CloudWatch Agent is running
  become: yes
  ansible.builtin.service:
    name: amazon-cloudwatch-agent
    state: restarted
