name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and AWS dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install ansible boto3 awscli
          ansible-galaxy collection install community.aws
          pip install -r app/requirements.txt
    
      - name: Install Ansible collections from requirements
        run: ansible-galaxy collection install -r ansible/requirements.yml


      - name: Debug Ansible collections and version
        run: |
          ansible-galaxy collection list | grep community.aws
          ansible --version

      - name: Debug role path and templates
        run: |
          echo "Role path: $(ansible-playbook -i ansible/inventory/hosts ansible/playbooks/roles/web/tasks/iam_setup.yml --list-tasks | grep role_path)"
          ansible-playbook -i ansible/inventory/hosts ansible/playbooks/roles/web/tasks/iam_setup.yml --check || echo "Template check failed"

      - name: Debug SSH key
        run: ls -l ~/.ssh/paper-social-key.pem

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Create IAM role and policy
        run: |
          ansible-playbook -i ansible/inventory/hosts ansible/playbooks/roles/web/tasks/iam_setup.yml || { echo "IAM setup failed, check logs"; exit 1; }

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i ansible/inventory/hosts ansible/playbooks/deploy.yml --private-key=~/.ssh/paper-social-key.pem --ssh-common-args='-o IdentitiesOnly=yes' -v
        env:
          ANSIBLE_HOST_KEY_CHECKING: false

      - name: Verify deployment
        run: curl http://paper-social-alb-1896686171.us-east-1.elb.amazonaws.com || echo "ALB check failed, verify manually"

      - name: Check CloudWatch Agent status
        run: |
          ssh -i ~/.ssh/paper-social-key.pem ec2-user@18.212.179.36 "sudo systemctl status amazon-cloudwatch-agent" || echo "SSH or status check failed for 18.212.179.36, check manually"
          ssh -i ~/.ssh/paper-social-key.pem ec2-user@54.167.152.195 "sudo systemctl status amazon-cloudwatch-agent" || echo "SSH or status check failed for 54.167.152.195, check manually"
